# pandas的数据结构介绍

In [1]:
import pandas as pd
from pandas import Series, DataFrame

## Series

Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
import numpy as np

In [9]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [12]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [14]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

sdata中跟states索引相匹配的那3个值会被找出来并放到相应的位置上，但由于"California"所对应的sdata值找不到，所以其结果就为NaN（即“非数字”（not a number），在pandas中，它用于表示缺失或NA值）。因为‘Utah’不在states中，它被从结果中除去

In [15]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [17]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series最重要的一个功能是，它会根据运算的索引标签自动对齐数据

In [21]:
obj4.name = 'population'
obj4.index.name = 'state'

In [22]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

* Series的索引可以通过赋值的方式就地修改

In [23]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

* 直接传入一个由等长列表或者NumPy数组组成的字典

In [25]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2003, 2004, 2005],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [26]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2003  2.4
4  Nevada  2004  2.9
5  Nevada  2005  3.2

In [27]:
frame.head() # 前五行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2003  2.4
4  Nevada  2004  2.9

In [28]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2003  Nevada  2.4
4  2004  Nevada  2.9
5  2005  Nevada  3.2

In [29]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

In [30]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2003  Nevada  2.4  NaN
five   2004  Nevada  2.9  NaN
six    2005  Nevada  3.2  NaN

In [31]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [32]:
frame2['year']

one      2000
two      2001
three    2002
four     2003
five     2004
six      2005
Name: year, dtype: int64

In [33]:
frame2.year

one      2000
two      2001
three    2002
four     2003
five     2004
six      2005
Name: year, dtype: int64

IPython提供了类似属性的访问（即frame2.year）和tab补全。 frame2[column]适用于任何列的名，但是frame2.column只有在列名是一个合理的Python变量名时才适用

In [34]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [35]:
frame2['debt'] = 16.5

In [36]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2003  Nevada  2.4  16.5
five   2004  Nevada  2.9  16.5
six    2005  Nevada  3.2  16.5

In [37]:
frame2['debt'] = np.arange(6.)

In [38]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2003  Nevada  2.4   3.0
five   2004  Nevada  2.9   4.0
six    2005  Nevada  3.2   5.0

In [39]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [40]:
frame2['debt'] = val

In [41]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2003  Nevada  2.4  -1.5
five   2004  Nevada  2.9  -1.7
six    2005  Nevada  3.2   NaN

如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值

In [42]:
frame2['eastern'] = frame2.state == 'Ohio'

In [43]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2003  Nevada  2.4  -1.5    False
five   2004  Nevada  2.9  -1.7    False
six    2005  Nevada  3.2   NaN    False

In [44]:
del frame2['eastern']

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

* 嵌套字典

In [46]:
pop = {'Nevada': {2001: 2.4, 2002:2.9},
      "Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [47]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [48]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

如果嵌套字典传给DataFrame，pandas就会被解释为：外层字典的键作为列，内层键则作为行索引

In [49]:
# pd.DataFrame(pop, index=[2001, 2002, 2003]) pandas版本问题，这种写法会报错
pd.DataFrame(pop, index=pd.Series([2001, 2002, 2003]))

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [50]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [51]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [52]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2003  Nevada  2.4  -1.5
five   2004  Nevada  2.9  -1.7
six    2005  Nevada  3.2   NaN

In [54]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2003, 'Nevada', 2.4, -1.5],
       [2004, 'Nevada', 2.9, -1.7],
       [2005, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

In [55]:
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])

In [56]:
index = obj.index

In [57]:
index

Index(['a', 'b', 'c'], dtype='object')

In [58]:
index[1:]

Index(['b', 'c'], dtype='object')

index对象是不可变的，因此用户不能对其进行修改

不可变可以使Index对象在多个数据结构之间安全共享：

In [59]:
labels = pd.Index(np.arange(3))

In [60]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [61]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [62]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [63]:
obj2.index is labels

True

In [64]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [65]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [66]:
'Ohio' in frame3.columns

True

In [67]:
2003 in frame3.index

False

In [68]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [69]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

pandas的Index可以包含重复的标签

## 基本功能

### 重新索引

In [70]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [71]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [72]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [73]:
obj3.reindex(np.arange(6), method='ffill') # 插值处理

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [74]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [75]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [76]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 丢弃指定轴上的项

In [77]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [78]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [79]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [80]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [82]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [84]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [86]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [87]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [88]:
obj.drop('c', inplace=True)

* 小心使用inplace

In [89]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

如果不指定，删除操作并不影响原来的DataFrame

### 索引、选取和过滤

In [90]:
obj = pd.Series(np.arange(4.0), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [91]:
obj_list = ['a', 'b', 'c', 'd']
obj_list

['a', 'b', 'c', 'd']

In [92]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [93]:
obj_list[1:2]

['b']

利用标签的切片运算与普通的Python切片运算不同，其末端是包含的

### 用loc和iloc进行选取

* 轴标签（loc）或整数索引（iloc）

In [94]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [96]:
data.iloc[1, [1, 2]]

two      5
three    6
Name: Colorado, dtype: int32

In [97]:
data.loc[:'Utah', :'two']

one  two
Ohio        0    1
Colorado    4    5
Utah        8    9

In [98]:
data.iloc[:2, :1]

one
Ohio        0
Colorado    4

In [99]:
data.iloc[:3, :2]

one  two
Ohio        0    1
Colorado    4    5
Utah        8    9

In [100]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### 整数索引

In [101]:
ser = pd.Series(np.arange(3.))

In [102]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [103]:
ser[-1] # 这种索引方式会出错，整数索引，前面的index 为0 1 2

KeyError: -1

In [104]:
ser[2] # 索引2存在

2.0

In [105]:
# 非整数索引不会出问题
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [106]:
ser2[-1]

2.0

为了进行统一，如果轴索引含有整数，数据选取总会使用标签。为了更准确，请使用loc（标签）或iloc（整数）

### 算数运算和数据对齐

In [107]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [108]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [109]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [110]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [111]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [112]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [113]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [114]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [115]:
df1 - df2

b   c    d   e
Colorado  NaN NaN  NaN NaN
Ohio     -3.0 NaN -2.0 NaN
Oregon    NaN NaN  NaN NaN
Texas    -3.0 NaN -2.0 NaN
Utah      NaN NaN  NaN NaN

如果DataFrame对象相加，没有共用的列或行标签，结果都会是空

### 在算术方法中填充值

In [117]:
df2.iloc[1, 2] = np.nan

In [118]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   NaN
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [119]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [120]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   NaN
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

### DataFrame和Series之间的运算

In [121]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [122]:
arr[0]

array([0., 1., 2., 3.])

In [123]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

当我们从arr减去arr[0]，每一行都会执行这个操作。这就叫做广播（broadcasting）

In [124]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [125]:
series = frame.iloc[0]

In [126]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [127]:
frame - series # 对应的索引能够匹配

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [128]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [129]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

如果某个索引值在DataFrame的列或Series的索引中找不到，则参与运算的两个对象就会被重新索引以形成并集

In [130]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [131]:
frame.sub(series3, axis='index') # axis=0亦可

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 函数应用和映射

* 行列级

In [132]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.188821  2.833608 -1.123526
Ohio   -0.116329  0.408748  2.254346
Texas   2.504953 -0.082737 -0.502622
Oregon  1.500935  0.407757 -0.275276

In [133]:
np.abs(frame)

b         d         e
Utah    0.188821  2.833608  1.123526
Ohio    0.116329  0.408748  2.254346
Texas   2.504953  0.082737  0.502622
Oregon  1.500935  0.407757  0.275276

In [134]:
f = lambda x: x.max() - x.min()

In [135]:
frame.apply(f)

b    2.693774
d    2.916345
e    3.377872
dtype: float64

In [136]:
frame.apply(f, axis='columns')

Utah      3.957134
Ohio      2.370675
Texas     3.007575
Oregon    1.776211
dtype: float64

In [137]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [138]:
frame.apply(f)

b         d         e
min -0.188821 -0.082737 -1.123526
max  2.504953  2.833608  2.254346

In [139]:
frame.apply(f, axis=1)

min       max
Utah   -1.123526  2.833608
Ohio   -0.116329  2.254346
Texas  -0.502622  2.504953
Oregon -0.275276  1.500935

* 元素级

In [140]:
format = lambda x: '%.2f' % x

In [141]:
frame.applymap(format)

b      d      e
Utah    -0.19   2.83  -1.12
Ohio    -0.12   0.41   2.25
Texas    2.50  -0.08  -0.50
Oregon   1.50   0.41  -0.28

之所以叫做applymap，是因为Series有一个用于应用元素级函数的map方法

In [142]:
frame['e'].map(format)

Utah      -1.12
Ohio       2.25
Texas     -0.50
Oregon    -0.28
Name: e, dtype: object

### 排序和排名

In [143]:
obj = pd.Series(range(4), index=list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [144]:
obj.sort_index

<bound method Series.sort_index of d    0
a    1
b    2
c    3
dtype: int64>

返回一个已排序的新对象

In [145]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [146]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [147]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [148]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [149]:
obj = pd.Series([4, 7, -3, 2])

In [150]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [152]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [153]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [154]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [155]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [156]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [157]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [158]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [159]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [160]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [161]:
obj[7] = 4

In [162]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
7    4
dtype: int64

In [163]:
obj.rank() # 4 的排名分别为4， 5， 6 取平均值5

0    7.5
1    1.0
2    7.5
3    5.0
4    3.0
5    2.0
6    5.0
7    5.0
dtype: float64

In [164]:
obj.rank(method='first')

0    7.0
1    1.0
2    8.0
3    4.0
4    3.0
5    2.0
6    5.0
7    6.0
dtype: float64

In [165]:
obj.rank(method='dense')

0    5.0
1    1.0
2    5.0
3    4.0
4    3.0
5    2.0
6    4.0
7    4.0
dtype: float64

### 带有重复标签的轴索引

In [166]:
obj = pd.Series(np.arange(5), index=list('aabbc'))
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [167]:
obj.index.is_unique # 判断索引是否唯一

False

In [168]:
obj['a']

a    0
a    1
dtype: int32

In [169]:
obj['c']

4

### 汇总和计算描述统计

In [171]:
df = pd.DataFrame([[1.4, np.nan],
                  [7.1, -4.5],
                  [np.nan, np.nan],
                  [0.75, -1.3]],
                 index=list('abcd'),
                 columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [172]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [173]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [174]:
df.sum(axis=1, skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [177]:
df.idxmax()

one    b
two    d
dtype: object

In [178]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [179]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

SyntaxError: invalid syntax (<ipython-input-180-990bbb6ee910>, line 1)